# theme.toml for the Airspace Hugo theme

name = "Airspace Hugo"
license = "CC BY 3.0"
licenselink = "https://github.com/themefisher/airspace-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisherâ€™s Airspace theme"
homepage = "https://github.com/themefisher/airspace-hugo"
tags = ["blog", "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher"]
features = ["blog", "company", "responsive"]
min_version = 0.19

[author]
  name = "Giacomo Mariani (@karjudev) for Themefisher"
  homepage = "https://themefisher.com/"

[original]
  name = "Airspace"
  homepage = "https://themefisher.com/products/airspace-free-bootstrap-website-template/"
  repo = "https://github.com/themefisher/airspace-free-html5-agency-template"
