######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/airspace/"
title = "Airspace | Creative Agency Hugo Template"
theme = "airspace-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "UTC"
# post pagination
paginate = "6" # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = "10" # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false # If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe= true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"